
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 3;
  public static final int RESERVADA_IMPORT = 50;
  public static final int SIGNO_DOS_PUNTOS = 54;
  public static final int RESERVADA_CLASS = 46;
  public static final int SENTENCIA_ELSE_IF = 30;
  public static final int VALOR_BOOLEANO = 10;
  public static final int CORCHETE_CERRADO = 58;
  public static final int RESERVADA_VOID = 47;
  public static final int ENTERO = 4;
  public static final int SENTENCIA_IF = 31;
  public static final int SIGNO_PUNTO_Y_COMA = 53;
  public static final int MATRIZ = 14;
  public static final int RESERVADA_PROTECTED = 43;
  public static final int OPERADOR_MENOR_QUE = 24;
  public static final int SENTENCIA_CONTINUE = 36;
  public static final int RESERVADA_PUBLIC = 41;
  public static final int OPERADOR_DE_ASIGNACION = 18;
  public static final int PARENTESIS_ABIERTO = 55;
  public static final int RESERVADA_PACKAGE = 49;
  public static final int LLAVE_ABIERTA = 59;
  public static final int CICLO_FOR = 40;
  public static final int SENTENCIA_CASE = 34;
  public static final int IDENTIFICADOR = 2;
  public static final int OPERADOR_DIFERENTE_DE = 22;
  public static final int CARACTER = 7;
  public static final int OPERADOR_MAYOR_IGUAL = 25;
  public static final int SIGNO_COMA = 52;
  public static final int VALOR_CADENA = 12;
  public static final int SENTENCIA_DEFAULT = 37;
  public static final int SENTENCIA_BREAK = 35;
  public static final int RESERVADA_FINAL = 44;
  public static final int CORCHETE_ABIERTO = 57;
  public static final int EOF = 0;
  public static final int NUMERO_FLOTANTE = 9;
  public static final int OPERADOR_MENOR_IGUAL = 26;
  public static final int ARREGLO = 13;
  public static final int error = 1;
  public static final int CADENA = 8;
  public static final int OPERADOR_OR = 28;
  public static final int VALOR_CARACTER = 11;
  public static final int CICLO_DO = 39;
  public static final int OPERADOR_INCREMENTO = 16;
  public static final int OPERADOR_AND = 27;
  public static final int OPERADOR_NOT = 29;
  public static final int RESERVADA_PRIVATE = 42;
  public static final int RESERVADA_STATIC = 45;
  public static final int SIGNO_PUNTO = 51;
  public static final int OPERADOR = 15;
  public static final int OPERADOR_DECREMENTO = 17;
  public static final int SENTENCIA_ELSE = 32;
  public static final int BOOLEANO = 6;
  public static final int PARENTESIS_CERRADO = 56;
  public static final int LLAVE_CERRADA = 60;
  public static final int OPERADOR_IGUAL_A = 21;
  public static final int OPERADOR_DE_ADICION = 19;
  public static final int OPERADOR_MAYOR_QUE = 23;
  public static final int CICLO_WHILE = 38;
  public static final int RESERVADA_RETURN = 48;
  public static final int SENTENCIA_SWITCH = 33;
  public static final int FLOTANTE = 5;
  public static final int OPERADOR_DE_SUSTRACCION = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "NUMERO",
  "ENTERO",
  "FLOTANTE",
  "BOOLEANO",
  "CARACTER",
  "CADENA",
  "NUMERO_FLOTANTE",
  "VALOR_BOOLEANO",
  "VALOR_CARACTER",
  "VALOR_CADENA",
  "ARREGLO",
  "MATRIZ",
  "OPERADOR",
  "OPERADOR_INCREMENTO",
  "OPERADOR_DECREMENTO",
  "OPERADOR_DE_ASIGNACION",
  "OPERADOR_DE_ADICION",
  "OPERADOR_DE_SUSTRACCION",
  "OPERADOR_IGUAL_A",
  "OPERADOR_DIFERENTE_DE",
  "OPERADOR_MAYOR_QUE",
  "OPERADOR_MENOR_QUE",
  "OPERADOR_MAYOR_IGUAL",
  "OPERADOR_MENOR_IGUAL",
  "OPERADOR_AND",
  "OPERADOR_OR",
  "OPERADOR_NOT",
  "SENTENCIA_ELSE_IF",
  "SENTENCIA_IF",
  "SENTENCIA_ELSE",
  "SENTENCIA_SWITCH",
  "SENTENCIA_CASE",
  "SENTENCIA_BREAK",
  "SENTENCIA_CONTINUE",
  "SENTENCIA_DEFAULT",
  "CICLO_WHILE",
  "CICLO_DO",
  "CICLO_FOR",
  "RESERVADA_PUBLIC",
  "RESERVADA_PRIVATE",
  "RESERVADA_PROTECTED",
  "RESERVADA_FINAL",
  "RESERVADA_STATIC",
  "RESERVADA_CLASS",
  "RESERVADA_VOID",
  "RESERVADA_RETURN",
  "RESERVADA_PACKAGE",
  "RESERVADA_IMPORT",
  "SIGNO_PUNTO",
  "SIGNO_COMA",
  "SIGNO_PUNTO_Y_COMA",
  "SIGNO_DOS_PUNTOS",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA"
  };
}

